#
# THIS FILE WILL BE OVERWRITTEN WITH THE PACKAGE UPDATE
# Use %APPDATA%/mpv/mpv.conf
# OR SVP's menu -> Information -> Add. information -> mpv config. file
#     to define your own customized configuration
#
# Sample mpv configuration
#

# this is required for SVP to "catch" the mpv
input-ipc-server=mpvpipe

# hardware video decoder
hwdec=auto-copy
hwdec-codecs=all

vo=gpu-next
gpu-api=d3d11
hwaccel=vaapi

############external config###########
cache=yes                               # uses a large seekable RAM cache even for local input.
cache-secs=300
border=no
osd-bar=no
osc=no
save-position-on-quit=yes
vlang=en,eng                            # Sets the video language
volume-max=150                          # maximum volume in %, everything above 100 results in amplification
volume=70
snap-window=yes                         # Enables windows snapping for Windows 10, 11
priority=high                           # Makes PC prioritize MPV for allocating resources
audio-pitch-correction=yes

##############colorcrap#############
lavfi-complex="[vf]eq=brightness=-10.0:contrast=7.0:saturation=10.0:gamma=1.0[vf]"


############externalSubtitleConfig#############
# Display English Subtitles if available
#sub-ass-force-margins=yes
#sub-ass-force-style=Kerning=yes        # allows you to override style parameters of ASS scripts
#sub-auto=fuzzy                         # external subs don't have to match the file name exactly to autoload
#sub-border-color="#FF262626"
#sub-border-size=3.0
#sub-color="#FFFFFFFF"
#sub-shadow-color="#33000000"
#sub-shadow-offset=1
#sub-spacing=0.5
#sub-use-margins=yes
alang=en,eng                            # default audio languages
embeddedfonts=yes                       # use embedded fonts for SSA/ASS subs
slang=en,eng                            # default subtitles languages                     # use yellow sub color (remove this line to make subtitles the default white colour)
sub-file-paths-append='Subs/${filename/no-ext}'      # search for external subs in these relative subdirectories
sub-file-paths-append='Subs/${filename}'
sub-file-paths-append='subs/${filename/no-ext}'
sub-file-paths-append='subs/${filename}'
sub-file-paths-append=ASS
sub-file-paths-append=Ass
sub-file-paths-append=SRT
sub-file-paths-append=Srt
sub-file-paths-append=Sub
sub-file-paths-append=Subs
sub-file-paths-append=Subtitles
sub-file-paths-append=ass
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles
sub-fix-timing=no                       # do not try to fix gaps (which might make it worse in some cases)
sub-scale-with-window=yes
sub-font="Arial"
sub-font-size=40
sub-auto=fuzzy                      # Load additional subtitle files containing the video filename
demuxer-mkv-subtitle-preroll=yes    # Try to correctly show embedded subs when seeking

# high quality video output, require rather fast video card
#profile=gpu-hq

# D3D11 renderer (default) is required for the HDR playback
#gpu-api=d3d11

# use VULKAN API if you have problems with the default d3d11 renderer
#gpu-api=vulkan

# miscellaneous options

# comment this one if you want mpv to remember the playback position
#save-position-on-quit=no

# fixes audio desync
hr-seek-framedrop=no

# "ReClock" replacement
#video-sync=display-resample
#video-sync-max-video-change=5

#log-file=mpv.log
